exclude: '.*\.svg$'
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.3
    hooks:
      - id: ruff
        types: [python]
      - id: ruff-format
        types: [python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: debug-statements
      - id: check-added-large-files
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: name-tests-test
        args: [--pytest-test-first]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        types: [python]
        additional_dependencies: [tokenize-rt==5.2.0, pydantic]
        exclude: tests

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.3
    hooks:
      - id: python-safety-dependencies-check
        files: pyproject.toml

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        types: [python]
        exclude: tests
        args: []

  # https://github.com/pre-commit/mirrors-eslint?tab=readme-ov-file#eslint-mirror
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.2.0 # Use latest release here
    hooks:
      - id: eslint
        exclude: .config.js$
        types_or: [javascript, jsx, ts, tsx, vue]
        additional_dependencies:
          - eslint@<9 # https://stackoverflow.com/a/78369728/9479128
          - eslint-plugin-vue@9.25.0
          - "@rushstack/eslint-patch@1.10.2"
          - "@vue/eslint-config-typescript@13.0.0"
          - "@babel/eslint-parser@7.24.5"
        args: ["--config", "frontend/.eslintrc.cjs"] # Point to config here

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, css, html, vue, json]
        additional_dependencies:
          - prettier@3.2.5 # SEE: https://github.com/pre-commit/pre-commit/issues/3133
        args: ["--config", "frontend/.prettierrc.json"]
